require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EstimationStatusesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # EstimationStatus. As you add validations to EstimationStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstimationStatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all estimation_statuses as @estimation_statuses" do
      estimation_status = EstimationStatus.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:estimation_statuses)).to eq([estimation_status])
    end
  end

  describe "GET show" do
    it "assigns the requested estimation_status as @estimation_status" do
      estimation_status = EstimationStatus.create! valid_attributes
      get :show, {:id => estimation_status.to_param}, valid_session
      expect(assigns(:estimation_status)).to eq(estimation_status)
    end
  end

  describe "GET new" do
    it "assigns a new estimation_status as @estimation_status" do
      get :new, {}, valid_session
      expect(assigns(:estimation_status)).to be_a_new(EstimationStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested estimation_status as @estimation_status" do
      estimation_status = EstimationStatus.create! valid_attributes
      get :edit, {:id => estimation_status.to_param}, valid_session
      expect(assigns(:estimation_status)).to eq(estimation_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EstimationStatus" do
        expect {
          post :create, {:estimation_status => valid_attributes}, valid_session
        }.to change(EstimationStatus, :count).by(1)
      end

      it "assigns a newly created estimation_status as @estimation_status" do
        post :create, {:estimation_status => valid_attributes}, valid_session
        expect(assigns(:estimation_status)).to be_a(EstimationStatus)
        expect(assigns(:estimation_status)).to be_persisted
      end

      it "redirects to the created estimation_status" do
        post :create, {:estimation_status => valid_attributes}, valid_session
        expect(response).to redirect_to(EstimationStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estimation_status as @estimation_status" do
        post :create, {:estimation_status => invalid_attributes}, valid_session
        expect(assigns(:estimation_status)).to be_a_new(EstimationStatus)
      end

      it "re-renders the 'new' template" do
        post :create, {:estimation_status => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested estimation_status" do
        estimation_status = EstimationStatus.create! valid_attributes
        put :update, {:id => estimation_status.to_param, :estimation_status => new_attributes}, valid_session
        estimation_status.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested estimation_status as @estimation_status" do
        estimation_status = EstimationStatus.create! valid_attributes
        put :update, {:id => estimation_status.to_param, :estimation_status => valid_attributes}, valid_session
        expect(assigns(:estimation_status)).to eq(estimation_status)
      end

      it "redirects to the estimation_status" do
        estimation_status = EstimationStatus.create! valid_attributes
        put :update, {:id => estimation_status.to_param, :estimation_status => valid_attributes}, valid_session
        expect(response).to redirect_to(estimation_status)
      end
    end

    describe "with invalid params" do
      it "assigns the estimation_status as @estimation_status" do
        estimation_status = EstimationStatus.create! valid_attributes
        put :update, {:id => estimation_status.to_param, :estimation_status => invalid_attributes}, valid_session
        expect(assigns(:estimation_status)).to eq(estimation_status)
      end

      it "re-renders the 'edit' template" do
        estimation_status = EstimationStatus.create! valid_attributes
        put :update, {:id => estimation_status.to_param, :estimation_status => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estimation_status" do
      estimation_status = EstimationStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => estimation_status.to_param}, valid_session
      }.to change(EstimationStatus, :count).by(-1)
    end

    it "redirects to the estimation_statuses list" do
      estimation_status = EstimationStatus.create! valid_attributes
      delete :destroy, {:id => estimation_status.to_param}, valid_session
      expect(response).to redirect_to(estimation_statuses_url)
    end
  end

end
