require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FactorsController do

  before do
    sign_in
    @connected_user = controller.current_user
  end

  before :each do
    @factor = FactoryGirl.create(:factor)
  end


  describe "GET index" do
    it "assigns all factors as @factors" do
      factor = @factor
      get :index, {}
      assigns(:factors).should eq([factor])
    end
  end

  describe "GET show" do
    it "assigns the requested factor as @factor" do
      factor = @factor
      get :show, {:id => factor.to_param}
      assigns(:factor).should eq(factor)
    end
  end

  describe "GET new" do
    it "assigns a new factor as @factor" do
      get :new, {}
      assigns(:factor).should be_a_new(Factor)
    end
  end

  describe "GET edit" do
    it "assigns the requested factor as @factor" do
      factor = @factor
      get :edit, {:id => factor.to_param}
      assigns(:factor).should eq(factor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Factor" do
        expect {
          post :create, {:factor => @factor.to_param}
        }.to change(Factor, :count).by(1)
      end

      it "assigns a newly created factor as @factor" do
        post :create, {:factor => @factor.to_param}
        assigns(:factor).should be_a(Factor)
        assigns(:factor).should be_persisted
      end

      it "redirects to the created factor" do
        post :create, {:factor => valid_attributes}
        response.should redirect_to(Factor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved factor as @factor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Factor.any_instance.stub(:save).and_return(false)
        post :create, {:factor => { "name" => "invalid value" }}
        assigns(:factor).should be_a_new(Factor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Factor.any_instance.stub(:save).and_return(false)
        post :create, {:factor => { "name" => "invalid value" }}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested factor" do
        factor = @factor
        # Assuming there are no other factors in the database, this
        # specifies that the Factor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Factor.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => factor.to_param, :factor => { "name" => "MyString" }}
      end

      it "assigns the requested factor as @factor" do
        factor = @factor
        put :update, {:id => factor.to_param, :factor => factor.to_param}
        assigns(:factor).should eq(factor)
      end

      it "redirects to the factor" do
        factor = @factor.to_param
        put :update, {:id => factor.to_param, :factor => factor.to_param}
        response.should redirect_to(factor)
      end
    end

    describe "with invalid params" do
      it "assigns the factor as @factor" do
        factor = @factor
        # Trigger the behavior that occurs when invalid params are submitted
        Factor.any_instance.stub(:save).and_return(false)
        put :update, {:id => factor.to_param, :factor => { "name" => "invalid value" }}
        assigns(:factor).should eq(factor)
      end

      it "re-renders the 'edit' template" do
        factor = @factor
        # Trigger the behavior that occurs when invalid params are submitted
        Factor.any_instance.stub(:save).and_return(false)
        put :update, {:id => factor.to_param, :factor => { "name" => "invalid value" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested factor" do
      factor = @factor
      expect {
        delete :destroy, {:id => factor.to_param}
      }.to change(Factor, :count).by(-1)
    end

    it "redirects to the factors list" do
      factor = @factor
      delete :destroy, {:id => factor.to_param}
      response.should redirect_to(factors_url)
    end
  end

end
